### ISSUE TITLE
Michael Whittaker

### ISSUE THREAD

**Issue by akatsarakis** [mwhittaker/craq_bug#1]
Hello Michael,

Cool corner case for CRAQ GC.
However, isn't this trivially solvable?

Assuming that each replica simply keeps the latest confirmed version (along with the most recent pending version). 
Then a reading replica that receives a delayed message from the tail (i.e., its "confirmed" version is higher) it simply returns the higher locally-confirmed version rather than the one specified in the message?

Thanks,
-Antonis

**Comment by mwhittaker** [comment]
Hey @akatsarakis! Thanks for checking out the repo :). Your fix sounds right to me!

**Comment by akatsarakis** [comment]
My pleasure, best of luck with your work. It seems quite interesting. :)
